stages:
  - manager
  - webhook
  - manifests

.manager:
  stage: manager
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.9.0
    entrypoint: [""]
  script:
    - /busybox/echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/controller:$CI_COMMIT_TAG
  only:
    - tags

.webhook:
  stage: webhook
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.9.0
    entrypoint: [""]
  script:
    - /busybox/echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.wh --destination $CI_REGISTRY_IMAGE/webhook:$CI_COMMIT_TAG
  only:
    - tags

manifests:
  stage: manifests
  image:
    name: gcr.io/triggermesh/kustomize
    entrypoint: [""]
  script:
    - "sed -i'' -e 's@image: .*@image: $CI_REGISTRY_IMAGE/controller:$CI_COMMIT_TAG@' ./config/default/manager_image_patch.yaml"
    - "sed -i'' -e 's@value: .*@value: $CI_REGISTRY_IMAGE/webhook:$CI_COMMIT_TAG@' ./config/default/manager_image_patch.yaml"
    - kustomize build config/default > release.yaml
  artifacts:
    paths:
    - release.yaml
  only:
    - tags
