apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources"]
    verbs: ["list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pipeline-runner-rolebinding
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
roleRef:
  kind: Role
  name: pipeline-runner-role
  apiGroup: rbac.authorization.k8s.io